sudo: required
service:
    - docker

before_instal:
    - docker build -t oresthazda/next-starter -f Dockerfile.dev . 

script:
    - docker run oresthazda/next-starter yarn test:ci

deploy:
    provider: elasticbeanstalk
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
    app: "next-starter"
    env: "NextStarter-env"
    region: "us-east-1"
    bucket_name: "elasticbeanstalk-us-east-1-888433145158"
    on:
        branch: master