version: "3"
services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev 
        ports: 
            - "3001:3000"
        volumes: 
            - /usr/app/node_modules
            - .:/usr/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /usr/app/node_modules
            - .:/usr/app
        command: ["yarn", "test:ci"]